In [22]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [23]:
# Load dataset
iris = load_iris()
X, y = iris.data, iris.target

In [24]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [25]:
# Standardize features (important for PCA)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [4]:
# Create and apply PCA
pca = PCA(n_components=2)  # Reduce to 2 dimensions
X_pca = pca.fit_transform(X_scaled)

In [5]:
# Analyze results
print(f"Original shape: {X.shape}")
print(f"Transformed shape: {X_pca.shape}")
print(f"Explained variance ratio: {pca.explained_variance_ratio_}")
print(f"Cumulative explained variance: {np.cumsum(pca.explained_variance_ratio_)}")
print(f"Principal components:\n{pca.components_}")

Original shape: (150, 4)
Transformed shape: (150, 2)
Explained variance ratio: [0.72962445 0.22850762]
Cumulative explained variance: [0.72962445 0.95813207]
Principal components:
[[ 0.52106591 -0.26934744  0.5804131   0.56485654]
 [ 0.37741762  0.92329566  0.02449161  0.06694199]]


In [6]:
# Determine optimal number of components
pca_full = PCA()
pca_full.fit(X_scaled)
cumsum = np.cumsum(pca_full.explained_variance_ratio_)
n_components = np.argmax(cumsum >= 0.95) + 1  # 95% variance threshold
print(f"Components needed for 95% variance: {n_components}")

Components needed for 95% variance: 2


In [27]:
cumsum

array([0.72962445, 0.95813207, 0.99482129, 1.        ])

In [29]:
X_pca

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [28]:
# Inverse transform (reconstruct data)
X_reconstructed = pca.inverse_transform(X_pca)
X_reconstructed

array([[-9.98888947e-01,  1.05319838e+00, -1.30270654e+00,
        -1.24709825e+00],
       [-1.33874781e+00, -6.19230225e-02, -1.22432772e+00,
        -1.22057235e+00],
       [-1.36096129e+00,  3.21116855e-01, -1.38060338e+00,
        -1.35833824e+00],
       [-1.42359795e+00,  6.77615022e-02, -1.34922386e+00,
        -1.33881298e+00],
       [-1.00113823e+00,  1.24091818e+00, -1.37125365e+00,
        -1.30661752e+00],
       [-5.19498709e-01,  1.93401703e+00, -1.16825103e+00,
        -1.07274520e+00],
       [-1.25551836e+00,  7.02282597e-01, -1.41737946e+00,
        -1.37733626e+00],
       [-1.07924053e+00,  8.07443319e-01, -1.29050848e+00,
        -1.24630034e+00],
       [-1.63744589e+00, -4.00947760e-01, -1.38237208e+00,
        -1.39339918e+00],
       [-1.31519294e+00,  1.55305022e-01, -1.27929958e+00,
        -1.26522875e+00],
       [-7.34883116e-01,  1.54712514e+00, -1.23179309e+00,
        -1.15378769e+00],
       [-1.16184140e+00,  7.49408049e-01, -1.34685751e+00,
      

In [30]:
X_reconstructed = scaler.inverse_transform(X_reconstructed)
X_reconstructed

array([[5.01894899, 3.51485426, 1.46601281, 0.25192199],
       [4.73846304, 3.03043329, 1.60391283, 0.27207352],
       [4.72013023, 3.19683002, 1.3289608 , 0.16741379],
       [4.66843611, 3.08676967, 1.38417005, 0.18224698],
       [5.01709266, 3.5964018 , 1.34541075, 0.20670563],
       [5.41459038, 3.89749154, 1.70257439, 0.38437671],
       [4.80715241, 3.3624126 , 1.26425682, 0.15298113],
       [4.95263473, 3.40809557, 1.48747414, 0.25252816],
       [4.49194713, 2.88315723, 1.32584895, 0.14077825],
       [4.7579029 , 3.12479954, 1.50719513, 0.23814838],
       [5.23683335, 3.72942146, 1.59077823, 0.32280933],
       [4.88446413, 3.38288441, 1.38833341, 0.20791797],
       [4.66234834, 3.02464414, 1.46116062, 0.2103005 ],
       [4.41151103, 2.97977531, 1.02769524, 0.02052641],
       [5.47717153, 4.0606523 , 1.59283856, 0.35040943],
       [5.70723141, 4.39947056, 1.56362285, 0.36518973],
       [5.35610979, 3.91069814, 1.56758271, 0.32746861],
       [5.05366832, 3.50968866,